### ISSUE TITLE
Gentoo: QA Notice ...

### ISSUE THREAD

**Issue by CaptainBloodz** [intel/gmmlib#72] opened 2020-08-13 21:19 UTC
UTC+3 here.
amd64 ~ # eix  media-libs/gmmlib
    Installed versions:  9999*l(00:02:38 14/08/2020)(ABI_MIPS="-n32 -n64 -o32" ABI_RISCV="-lp64 -lp64d" ABI_S390="-32 -64" ABI_X86="64 -32 -x32")

End of below build log returns: 
 * QA Notice: Package triggers severe warnings which indicate that it
 *            may exhibit random runtime failures.
 * /var/tmp/portage/media-libs/gmmlib-9999/work/gmmlib-9999/Source/GmmLib/TranslationTable/GmmPageTableMgr.cpp:415:50: warning: converting to non-pointer type 'long unsigned int' from NULL [-Wconversion-null]
 * /var/tmp/portage/media-libs/gmmlib-9999/work/gmmlib-9999/Source/GmmLib/TranslationTable/GmmPageTableMgr.cpp:474:31: warning: NULL used in arithmetic [-Wpointer-arith]

[media-libs:gmmlib-9999:20200813-210138.log.zip](https://github.com/intel/gmmlib/files/5071442/media-libs.gmmlib-9999.20200813-210138.log.zip)

building environment details:

amd64 ~ # emerge --info gmmlib
sh bash 5.0_p17
ld GNU ld (Gentoo 2.33.1 p2) 2.33.1
distcc 3.3.3 x86_64-pc-linux-gnu [disabled]
app-shells/bash:          5.0_p17::gentoo
dev-java/java-config:     2.3.1::gentoo
dev-lang/perl:            5.30.3::gentoo
dev-lang/python:          2.7.18-r1::gentoo, 3.6.11-r2::gentoo, 3.7.8-r2::gentoo, 3.8.4-r1::gentoo
dev-util/cmake:           3.16.5::gentoo
dev-util/pkgconfig:       0.29.2::gentoo
sys-apps/baselayout:      2.6-r1::gentoo
sys-apps/openrc:          0.42.1::gentoo
sys-apps/sandbox:         2.18::gentoo
sys-devel/autoconf:       2.13-r1::gentoo, 2.69-r4::gentoo
sys-devel/automake:       1.16.1-r1::gentoo
sys-devel/binutils:       2.33.1-r1::gentoo
sys-devel/gcc:            9.3.0-r1::gentoo, 10.2.0::gentoo
sys-devel/gcc-config:     2.3.1::gentoo
sys-devel/libtool:        2.4.6-r6::gentoo
sys-devel/make:           4.2.1-r4::gentoo
sys-kernel/linux-headers: 5.7::gentoo (virtual/os-headers)
sys-libs/glibc:           2.31-r6::gentoo

ACCEPT_KEYWORDS="amd64"
ACCEPT_LICENSE="* -@EULA"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-march=skylake -mtune=skylake   -O2             -pipe -ftree-loop-vectorize -ftree-slp-vectorize  "
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/php/apache2-php7.4/ext-active/ /etc/php/cgi-php7.4/ext-active/ /etc/php/cli-php7.4/ext-active/ /etc/revdep-rebuild /etc/sandbox.d /etc/splash /etc/terminfo /etc/texmf/language.dat.d /etc/texmf/language.def.d /etc/texmf/updmap.d /etc/texmf/web2c"
CXXFLAGS="-march=skylake -mtune=skylake   -O2             -pipe -ftree-loop-vectorize -ftree-slp-vectorize      "
DISTDIR="/var/cache/distfiles"
EMERGE_DEFAULT_OPTS="--alert y 			--alphabetical 			--ask-enter-invalid 			--autounmask y  			--autounmask-only n  			--autounmask-unrestricted-atoms y  		--autounmask-write y 			--misspell-suggestions n 			--noconfmem 			--nospinner   			--tree 			--with-bdeps y"
ENV_UNSET="DBUS_SESSION_BUS_ADDRESS DISPLAY GOBIN GOPATH PERL5LIB PERL5OPT PERLPREFIX PERL_CORE PERL_MB_OPT PERL_MM_OPT XAUTHORITY XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_RUNTIME_DIR"
FCFLAGS="-march=skylake -mtune=skylake   -O2             -pipe -ftree-loop-vectorize -ftree-slp-vectorize  "
FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync multilib-strict network-sandbox news parallel-fetch pid-sandbox preserve-libs protect-owned qa-unresolved-soname-deps sandbox sfperms split-elog strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync"
FFLAGS="-march=skylake -mtune=skylake   -O2             -pipe -ftree-loop-vectorize -ftree-slp-vectorize  "

LANG="fr_FR.utf8"
LDFLAGS="  -Wl,-O1       -Wl,-fuse-ld=bfd  -Wl,--enable-new-dtags  -Wl,-z,relro -Wl,-z,now -fno-plt -march=skylake -mtune=skylake   -O2             -pipe -ftree-loop-vectorize -ftree-slp-vectorize   "
LINGUAS="fr"
MAKEOPTS="-j3 -l3"

USE="amd64 asm libglvnd minimal split-usr" ABI_X86="64" ALSA_CARDS="hda-intel" CPU_FLAGS_X86="aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3" ELIBC="glibc" GRUB_PLATFORMS="pc" INPUT_DEVICES="libinput" KERNEL="linux" L10N="fr" PHP_TARGETS="php7-4" PYTHON_SINGLE_TARGET="python3_7" PYTHON_TARGETS="python2_7 python3_6 python3_7" QEMU_USER_TARGETS="aarch64" RUBY_TARGETS="ruby25" USERLAND="GNU" VIDEO_CARDS="intel i965"
Unset:  CC, CPPFLAGS, CTARGET, CXX, INSTALL_MASK, LC_ALL, PORTAGE_BINHOST, PORTAGE_BUNZIP2_COMMAND, PORTAGE_RSYNC_EXTRA_OPTS

                        Package Settings

media-libs/gmmlib-9999::gentoo was built with the following:
USE="" ABI_X86="-32 (64) (-x32)"

Thks 4 ur attention, interest & support

**Comment by edwarddavidbaker** [comment] 2021-02-24 16:46
Seems like a duplicate of issue #62 and #61.

**Comment by johnmach** [comment] 2023-01-13 19:16
Fixed in https://github.com/intel/gmmlib/commit/5647e870efe9f57bec1db10fea04d6d4126747a0

**Closed by johnmach** 2023-01-13 19:16 UTC
